// ********************************
// This file is generated by a tool
// ********************************

import { interpolate } from "../translation-utils";
import { ILanguage } from "./language.interface";
import * as Sections from "./section.interface";

// Sections

// Language

export const enca: ILanguage = {
  metadata: {
    shortcode: "en-ca",
    name: "English (CA)"
  },
};

export default enca;
