// ********************************
// This file is generated by a tool
// ********************************

import { interpolate } from "../translation-utils";
import { ILanguage } from "./language.interface";
import * as Sections from "./sections.interface";

// Sections

export const _componentsTabsRepositoryBranches: Sections.IComponentsTabsRepositoryBranches = {
  title: "Local branches",
  branchContextMenu: {
    checkout: (branch: string) => interpolate("Checkout ${branch}", { branch }),
  },

};

// Language

export const engb: ILanguage = {
  metadata: {
    shortcode: "en-gb",
    name: "English (UK)"
  },
  "components-tabs-repository-branches": _componentsTabsRepositoryBranches,
};

export default engb;
