// ********************************
// This file is generated by a tool
// ********************************

import { interpolate } from "../translation-utils";
import { ILanguage } from "./language.interface";
import * as Sections from "./sections.interface";
import * as engb from "./en-gb";

// Sections

export const _componentsTabsRepositoryBranches: Sections.IComponentsTabsRepositoryBranches = {
  title: "Local branchessssssssssss",
  branchContextMenu: engb._componentsTabsRepositoryBranches.branchContextMenu,

};

// Language

export const enus: ILanguage = {
  metadata: {
    shortcode: "en-us",
    name: "English (US)"
  },
  "components-tabs-repository-branches": _componentsTabsRepositoryBranches,
};

export default enus;
