// ********************************
// This file is generated by a tool
// ********************************

import { interpolate } from "../translation-utils";
import { ILanguage } from "./language.interface";
import * as Sections from "./section.interface";

// Sections

export const _componentsTabsRepositoryBranches: Sections.IComponentsTabsRepositoryBranches = {
title: "Local branchessssssssssss",
};

// Language

export const enus: ILanguage = {
  metadata: {
    shortcode: "en-us",
    name: "English (US)"
  },
};

export default enus;
