// ********************************
// This file is generated by a tool
// ********************************

import { StringTranslation } from "../types/translations";

// Sections

export interface IComponentsTabsRepositoryBranches {
  title: StringTranslation;
  branchContextMenu: {
    checkout: (branch: string) => string;
  };
}
